# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b37910ed1934c9e3e9b771c0617bfbdd8dfed121b9127b4c7bd215047e53c3387f7d4a08eedf8b0b9921a1a06b65acf48c5287a3fb1db90da9a37e0899ddc9a4

test:
  secret_key_base: 15a4c2c1e2331f502644b3d79cd2405647ae657feda191872f510c1f69d9bc80aad3f2d72e1b118caf257c0ba55a668094d2ceedf878b6d87cbac0b7b7ff82bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
